@hostname = localhost
@port = 8090
@protocol = http
@host = {{protocol}}://{{hostname}}:{{port}}
@contentType = application/json
@basic = Basic YWRtaW46YWRtaW4xMjM=
@bearer = Bearer bf1868428ad0921bfb5b328571be3cdeacc162b10688062be3b5e36b2195e2fa

### Get health status
GET {{host}}/health

### Login user (admin)
POST {{host}}/auth/login
Content-Type: {{contentType}}

{
    "username": "admin",
    "password": "admin123"
}

### Login user (admin)
POST {{host}}/auth/login
Authorization: {{basic}}

### Logout user (admin)
POST {{host}}/auth/logout
Authorization: {{bearer}}

### Get all roles
GET {{host}}/admin/roles
Authorization: {{basic}}

### Crete a new read only user
POST {{host}}/admin/users
Content-Type: {{contentType}}
Authorization: {{basic}}

{
    "username": "reader",
    "password": "readerPass123",
    "role_ids": ["cb65106d-fd17-4933-9a32-92a3eb9fa1fd"]
}

### Crete a new read-write user
POST {{host}}/admin/users
Content-Type: {{contentType}}
Authorization: {{bearer}}

{
    "username": "writer",
    "password": "writerPass123",
    "role_ids": ["b8405258-7fde-4266-8967-5d279f7011e5"]
}

### Get all users
GET {{host}}/admin/users
Authorization: {{bearer}}

### Get user by username
GET {{host}}/admin/users/reader
Authorization: {{bearer}}

### Delete user by username
DELETE {{host}}/admin/users/reader
Authorization: {{bearer}}

### Get all caches
GET {{host}}/admin/caches
Authorization: {{bearer}}

### Create a new cache with time to live based eviction
POST {{host}}/admin/caches
Content-Type: {{contentType}}
Authorization: {{bearer}}

{
    "name": "test-timed",
    "description": "Time-based cache with 1 minute TTL",
    "tags": {"env": "production", "type": "ttl"},
    "eviction": "ttl",
    "default_ttl_ms": 60000
}

### Create a new cache with storage size based eviction
POST {{host}}/admin/caches
Content-Type: {{contentType}}
Authorization: {{bearer}}

{
    "name": "test-sized",
    "description": "Size-based cache with 1 MB memory limit",
    "tags": {"env": "production", "type": "size"},
    "eviction": "size",
    "mem_bytes": 1048576
}

### Describe a cache
GET {{host}}/admin/caches/test-sized
Authorization: {{bearer}}

### Drop a cache
DELETE {{host}}/admin/caches/test-sized
Authorization: {{bearer}}

### Put an entry into a cache
PUT {{host}}/cache/test-timed/1
Content-Type: {{contentType}}
Authorization: {{bearer}}

{
    "value": "hello world"
}

### Get an entry from the cache
GET {{host}}/cache/test-timed/1
Authorization: {{bearer}}

### Delete an entry from the cache
DELETE {{host}}/cache/test-timed/1
Authorization: {{bearer}}

### Create a new cache with time to live based eviction
POST {{host}}/admin/caches
Content-Type: {{contentType}}
Authorization: {{bearer}}

{
    "name": "perf-test",
    "description": "Time-based cache with 1 minute TTL",
    "tags": {"env": "production", "type": "ttl"},
    "eviction": "ttl",
    "default_ttl_ms": 60000
}